JAZZMIN_SETTINGS = {
    "site_title": "CloudCake Admin",
    "site_header": "Cloud Cake & Foods",
    "site_brand": "Cloud Cake & Foods",
    "site_logo": "/assets/img/gallery/cc_icon.jpg",
    "login_logo": None,
    "login_logo_dark": None,
    "site_logo_classes": "navbar-brand-logo",
    "site_icon": None,
    "welcome_sign": "Welcome to Cloud Cake & Foods",
    "copyright": "Cloud Cake & Foods",
    "user_avatar": None,
    "show_sidebar": True,
    "navigation_expanded": True,
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
    "related_modal_active": False,
    "custom_css": "/assets/css/admin.css",  # Ensure this path is correct
    "custom_js": None,
    "use_google_fonts_cdn": True,
    "show_ui_builder": False,
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {"auth.user": "collapsible", "auth.group": "vertical_tabs"},
}
