# Generated by Django 4.2.7 on 2024-05-24 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
