# Generated by Django 4.2.7 on 2024-05-26 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_detail_product_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='cart_items',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
