# Generated by Django 4.2.7 on 2024-05-27 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_contact_cart_items'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Order',
        ),
    ]
