# Generated by Django 4.2.7 on 2024-05-27 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_rename_contact_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
    ]
