# Generated by Django 4.2.7 on 2024-05-29 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_order_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddCart',
        ),
    ]
