# Generated by Django 4.2.7 on 2024-06-08 04:49

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_product_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='detail',
            field=django_ckeditor_5.fields.CKEditor5Field(max_length=1200, null=True),
        ),
    ]
