# Generated by Django 4.2.7 on 2024-06-11 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_outlet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outlet',
            name='iframe_url',
            field=models.URLField(max_length=300),
        ),
    ]
