# Generated by Django 4.2.7 on 2024-06-11 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_alter_outlet_iframe_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outlet',
            name='iframe_url',
        ),
        migrations.AddField(
            model_name='outlet',
            name='map_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='outlet',
            name='address',
            field=models.TextField(null=True),
        ),
    ]
