# Generated by Django 4.2.7 on 2024-06-11 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_remove_outlet_iframe_url_outlet_map_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outlet',
            name='map_url',
        ),
        migrations.AddField(
            model_name='outlet',
            name='map_iframe',
            field=models.TextField(null=True),
        ),
    ]
