# Generated by Django 4.2.7 on 2024-07-31 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_alter_career_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('cake', 'Cake'), ('bread', 'Bread'), ('savory', 'Savory'), ('frozen', 'Frozen')], max_length=20, unique=True)),
                ('image', models.ImageField(upload_to='category_images/')),
            ],
        ),
    ]
