# Generated by Django 4.2.7 on 2024-08-12 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_categoryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='outlet_images/'),
        ),
    ]
