# Generated by Django 4.2.7 on 2024-09-04 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_fooditems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditems',
            name='mrp',
            field=models.IntegerField(default=0),
        ),
    ]
