# Generated by Django 4.2.7 on 2024-09-04 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_alter_fooditems_mrp'),
    ]

    operations = [
        migrations.CreateModel(
            name='MRP_Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
            ],
        ),
    ]
