# Generated by Django 4.2.7 on 2024-09-04 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_mrp_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mrp_logo',
            name='image',
            field=models.ImageField(default='No image uploaded', upload_to='logos/'),
        ),
    ]
