# Generated by Django 4.2.7 on 2024-09-04 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_alter_mrp_logo_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MRP_Logo',
        ),
    ]
