# Generated by Django 4.2.7 on 2024-09-29 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0035_alter_order_address_alter_order_total_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_amount',
        ),
    ]
