# Generated by Django 4.2.7 on 2024-09-29 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0037_order_is_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_new',
        ),
    ]
