# Generated by Django 4.2.7 on 2024-09-30 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0039_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
