# Generated by Django 4.2.7 on 2024-10-26 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0040_delete_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Processing', 'Processing'), ('Completed', 'Completed'), ('Cancel', 'Cancel')], default='Processing', max_length=10),
        ),
    ]
